# Generated by Django 3.0.3 on 2020-03-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ulr',
            new_name='url',
        ),
    ]
